version: '3.7'

services:
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
  nats:
    image: lennonsaves/nats
    ports:
      - 4222:4222
      - 9222:9222
  indexer:
    image: delphaireview.azurecr.io/indexer:index-labels
    volumes:
      - $HOME/.kube/config:/root/.kube/config
    ports:
      - 8888:8080
      - 7777:7070
    environment:
      DELPHAI_ENVIRONMENT: development
