logger:
  name: delphai
  level: INFO

apiBaseUrl: https://api.delphai.blue/indexer

redis:
  host: redis.redis
  port: 6379

nats:
  url: nats://nats:4222
  json: false

database:
  connectionString: ${DATABASE_CONNECTION_STRING}
  database: main

indexer:
  address: indexer-grpc:8080

server:
  port: 8080
